### ISSUE TITLE
TeaVM compilation error (preview builds, WASM target)

### ISSUE THREAD

**Issue by WorldEditAxe** [konsoletyper/teavm#739]
Hi, I attempted to compile a TeaVM project using version `0.9.0-dev-12` of `teavm-gradle-plugin` under OpenJDK `20.0.2`. However, compiling my project resulted in an error being thrown by TeaVM (see here: https://pastebin.com/M6tYXuHy, ran with `--stacktrace`). What might be the root cause of this?

**Comment by konsoletyper** [comment]
Hello. Have no idea. If it's possible, please, share your project so that I could reproduce issue myself.

**Comment by konsoletyper** [comment]
BTW, from stack trace I can see that you are using fast dependency analysis. What was the reason to do that? Did you try to switch it off?

**Comment by WorldEditAxe** [comment]
1. I am unable to publicly share the source code, but I am willing to do so through a private channel. Can you provide a method of private contact?
2. I've turned this on only to make compile times faster, as the project I am using TeaVM on is fairly huge. I've turned this off, but now I get a new build exception: https://pastebin.com/qFkJ4LdZ.

BTW, the project utilizes JSO (and related APIs). I understand that this may not be supported, but the nature of this issue warrants for an issue report. The compiler should be able to identify the reason of failure and provide it in a human-readable format.

**Comment by konsoletyper** [comment]
You are right, but remember that WASM has "experimental" status, thus isn't very stable.

You can join TeaVM gitter (see badge) and send me a personal message.

**Comment by konsoletyper** [comment]
The error in case with fast dependency analysis turned off is a tough one, I'm still trying to fix it. It's related to transformation of regular program into coroutine state machine in order to emulate threads. I spent many months polishing this feature for JS, but for Wasm I simply could not deal with such complicated code bases utilizing threads and synchronization. Recently I pushed 1cd635afa5d6646dbc3b5684712a8ca3ed7a0e73 that fixes that problem partially, but still there are some cases that cause this error (nothing changes on your side, you still get similar errors). Please, be patient!

**Comment by WorldEditAxe** [comment]
That's okay, take your time. Do you think any changes will have to be made on my end to resolve this issue?

**Comment by konsoletyper** [comment]
I fixed the problems that prevented the build in precise dependency analysis mode. However, it only works with modified version of your code base. I removed most of `@Async` methods. Without this modification TeaVM crashes with OOME, and I have no idea how to fix it: it's not an bug, it's a design issue, and I need months of research and then months of refactoring. Anyway, if you are looking for better performance, you should get rid of `@Async` methods, and I should say that in all cases it's possible (but it will cost you memory). So, without these asyncs WebAssembly BE does not crash, but produces error messages related to usages of `@JSBody` annotation, which is obviously not supported.

As for WebAssembly in general: if you expect dramatic performance increase, you'll be disappointed. To improve performance, you should start with following steps:

1. Build without obfuscation
2. Run browser profiler, take profile and see what are the bottlenecks. You can use both top-down and bottom-up trees to identify them.
3. Fix these bottlenecks yourself or tell me if TeaVM produces slow code or has slow emulation of JDK classes
4. *Avoid* asyncs when possible. To gain maximum performance, avoid asyncs at all. Don't use other synchronization primitives that use Async inside, e.g. Object.wait, etc.
5. I found that your build configuration defines 'AGGRESSIVE' optimization level for alls targets. Please, don't. You better avoid setting optimizationLevel directly, unless you understand what you doing. Gradle plugin comes with reasonable defaults, and default value for JS is 'BALANCED'.

**Comment by WorldEditAxe** [comment]
Okay, I've noticed that JRE emulation via TeaVM through JavaScript is generally slow, and this is what I am attributing performance issues to. There seems to be a 2-5x slowdown in performance when using TeaVM's JS compiler (compared to the original game), so I am looking for ways to further lower the overhead caused by TeaVM. For this reason, I've decided to investigate methods to further optimize the compiled output, hence why I decided to look into WebAssembly. So, what should I expect from using WASM BE? *Any* performance boost would be beneficial, since a lot of in-game lag is the result of a CPU bottleneck. I will look into your suggestions to better improve performance. Profiling and optimization has been done in the past - I believe there is no longer much to optimization other than doing aggressive microoptimizations.

Thank you for your contributions!

**Comment by WorldEditAxe** [comment]
> I fixed the problems that prevented the build in precise dependency analysis mode. However, it only works with modified version of your code base. I removed most of `@Async` methods. Without this modification TeaVM crashes with OOME, and I have no idea how to fix it: it's not an bug, it's a design issue, and I need months of research and then months of refactoring. Anyway, if you are looking for better performance, you should get rid of `@Async` methods, and I should say that in all cases it's possible (but it will cost you memory). So, without these asyncs WebAssembly BE does not crash, but produces error messages related to usages of `@JSBody` annotation, which is obviously not supported.
> 
> As for WebAssembly in general: if you expect dramatic performance increase, you'll be disappointed. To improve performance, you should start with following steps:
> 
> 1. Build without obfuscation
> 2. Run browser profiler, take profile and see what are the bottlenecks. You can use both top-down and bottom-up trees to identify them.
> 3. Fix these bottlenecks yourself or tell me if TeaVM produces slow code or has slow emulation of JDK classes
> 4. _Avoid_ asyncs when possible. To gain maximum performance, avoid asyncs at all. Don't use other synchronization primitives that use Async inside, e.g. Object.wait, etc.
> 5. I found that your build configuration defines 'AGGRESSIVE' optimization level for alls targets. Please, don't. You better avoid setting optimizationLevel directly, unless you understand what you doing. Gradle plugin comes with reasonable defaults, and default value for JS is 'BALANCED'.

Apparently, no, removing all asyncs from my code did not fix the underlying WASM compilation failure. While TeaVM successfully compiled to the C target, it still ran out of memory without any `@Async` references in the code whatsoever when targeting WASM. Can you provide a list of classes (or methods) with references to the annotation so I can go through them myself and work around them?

**Comment by konsoletyper** [comment]
How much memory do you give to TeaVM compiler?

**Comment by konsoletyper** [comment]
You can also enable out-of-process mode and as compiler crashes it should write hprof file. You can send it to me.

**Comment by WorldEditAxe** [comment]
1. 8 gigabytes of RAM (set via `org.gradle.jvmargs=-Xmx8G` in `gradle.properties`)
2. Check your Gitter - I have direct messaged you with the download link.
